export const COLORS = {
  BLUE_LIGHT: "#D9F1FF",
  BLUE_REGULAR: "#AFE2FF",
  BLUE_BOLD: "#2C8BB6",
  BLUE_EXTRA_BOLD: "#083245",
  YELLOW: "#FFAC45",
  GREEN: "#1AA213",
  GREY_LIGHT: "#D1D1D1",
  GREY_REGULAR: "#CACACA",
  WHITE: "#FFFFFF",
}